"""Schemas for full run reports and request payloads."""

from __future__ import annotations

from datetime import date, datetime

from pydantic import BaseModel, Field, field_validator

from schemas.experiment import ExperimentPlan
from schemas.hypothesis import Hypothesis
from schemas.paper import Paper
from schemas.result import ExperimentResult
from schemas.strategy import StrategyUpdate


class ResearchConstraints(BaseModel):
    """Optional run constraints supplied by the user."""

    date_from: date | None = None
    date_to: date | None = None
    max_papers: int = 12
    preferred_categories: list[str] = Field(default_factory=list)
    experiment_budget: int = 2
    experiments_enabled: bool = True

    @field_validator("max_papers")
    @classmethod
    def validate_max_papers(cls, value: int) -> int:
        if value < 1 or value > 100:
            raise ValueError("max_papers must be between 1 and 100")
        return value

    @field_validator("experiment_budget")
    @classmethod
    def validate_experiment_budget(cls, value: int) -> int:
        if value < 0 or value > 20:
            raise ValueError("experiment_budget must be between 0 and 20")
        return value


class ResearchRequest(BaseModel):
    """User-provided request that starts a research cycle."""

    topic: str
    constraints: ResearchConstraints = Field(default_factory=ResearchConstraints)


class RunSummary(BaseModel):
    """Quick summary counters for the run."""

    started_at: datetime
    completed_at: datetime
    papers_retrieved: int
    papers_ranked: int
    hypotheses_generated: int
    experiments_attempted: int
    experiments_executed: int


class RunReport(BaseModel):
    """Final report object generated by the workflow."""

    run_id: str
    topic: str
    constraints: ResearchConstraints
    summary: RunSummary
    retrieved_papers: list[Paper] = Field(default_factory=list)
    hypotheses: list[Hypothesis] = Field(default_factory=list)
    experiment_plans: list[ExperimentPlan] = Field(default_factory=list)
    experiment_results: list[ExperimentResult] = Field(default_factory=list)
    strategy_updates: list[StrategyUpdate] = Field(default_factory=list)
    reflection_notes: list[str] = Field(default_factory=list)
    next_research_ideas: list[str] = Field(default_factory=list)
    report_markdown_path: str = ""
    report_json_path: str = ""
